prevent removal of ecryptfs-utils package, if in use
debian/ecryptfs-utils.prerm: perform some cursory checks, to ensure that
there are no obvious, current users of ecryptfs before allowing package
removal, Bug #331085

Signed-off-by: Dustin Kirkland <kirkland@canonical.com>

diff --git a/debian/ecryptfs-utils.prerm b/debian/ecryptfs-utils.prerm
--- a/debian/ecryptfs-utils.prerm
+++ b/debian/ecryptfs-utils.prerm
@@ -1,6 +1,35 @@
 #!/bin/sh -e
 
 if [ "$1" = remove ]; then
+	# We must do some checking to prevent removal of ecryptfs if in use
+	# Check active mounts
+	if out=`mount | grep "\Wtype\Wecryptfs\W"`; then
+		echo "ERROR: Cannot remove ecryptfs-utils, as it appears to be in use:" 1>&2
+		echo "$out" 1>&2
+		exit 1
+	fi
+	if out=`grep "\Wecryptfs\W" /proc/mounts`; then
+		echo "ERROR: Cannot remove ecryptfs-utils, as it appears to be in use:" 1>&2
+		echo "$out" 1>&2
+		exit 1
+	fi
+	# Check fstab
+	if out=`grep "\Wecryptfs\W" /etc/fstab`; then
+		echo "ERROR: Cannot remove ecryptfs-utils, as it appears to be in use:" 1>&2
+		echo "$out" 1>&2
+		exit 1
+	fi
+	# Check home directories
+	for i in `ls /home`; do
+		if [ -d "/home/$i/.ecryptfs" ]; then
+			# If we find a .ecryptfs directory (or link) in a home,
+			# directory, then someone is using ecryptfs-utils, and
+			# we should not allow package removal
+			echo "ERROR: Cannot remove ecryptfs-utils, as it appears to be in use:" 1>&2
+			echo "       [/home/$i/.ecryptfs]" 1>&2
+			exit 1
+		fi
+	done
 	pam-auth-update --package --remove ecryptfs-utils
 fi
 
