* src/utils/ecryptfs-mount-private, src/utils/ecryptfs-rewrite-file,     src/utils/ecryptfs-setup-private, src/utils/ecryptfs-setup-swap,     src/utils/ecryptfs-umount-private: use gettext for all string printing,     such that we can internationalize ecryptfs
Signed-off-by: Dustin Kirkland <kirkland@canonical.com>

diff --git a/src/utils/ecryptfs-rewrite-file b/src/utils/ecryptfs-rewrite-file
--- a/src/utils/ecryptfs-rewrite-file
+++ b/src/utils/ecryptfs-rewrite-file
@@ -17,57 +17,59 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+TEXTDOMAIN="ecryptfs-utils"
+
 error() {
-	echo "[FAILED]"
-	echo "ERROR: $1" 1>&2
+	echo `gettext "[FAILED]"`
+	echo `gettext "ERROR:"` "$1" 1>&2
 }
 j=0
 OKs=0
 for i in "$@"; do
 	j=`expr $j + 1`
-	echo -n "INFO: Rewriting [$j/$#] [$i] ... "
+	echo -n `gettext "INFO:"` `gettext "Rewriting"` "[$j/$#] [$i] ... "
 	if [ ! -e "$i" ] ; then
-		error "File does not exists"
+		error `gettext "File does not exist"`
 		continue
 	fi
 	if [ "$i" = "." ]; then
-		echo "[EXCLUDED]" >&2
+		echo `gettext "[EXCLUDED]"` >&2
 		continue
 	fi
 	opt=
 	if [ -d "$i" -a ! -h "$i" ]; then
 		# A directory, re-encrypt the filename
 		temp1=`mktemp -d "$i".XXXXXXXXXX` || {
-			error "Could not create tempdir"
+			error `gettext "Could not create tempdir"`
 			continue
 		}
 		mv -f -T "$i" "$temp1" 2>/dev/null  || {
-			error "Could not rename [$i] to [$temp1]"
+			error `gettext "Could not rename"` "[$i] -> [$temp1]"
 			rmdir "$temp1"
 			continue
 		}
 		mv -f "$temp1" "$i" 2>/dev/null || {
-			error "Could not rename [$temp1] to [$i]"
+			error `gettext "Could not rename"` "[$temp1] -> [$i]"
 		}
 	else
 		# A file or symlink, re-encrypt the contents
 		temp1=`mktemp "$i".XXXXXXXXXX` || {
-			error "Could not create tempfile"
+			error `gettext "Could not create tempfile"`
 			continue
 		}
 		cp -a "$i" "$temp1" 2>/dev/null || {
-			error "Could not copy [$i] to [$temp1]"
+			error `gettext "Could not copy"` "[$i] -> [$temp1]"
 			rm -f "$temp1"
 			continue
 		}
 		mv -f "$temp1" "$i" 2>/dev/null || {
-			error "Could not rename [$temp1] to [$i]"
+			error `gettext "Could not rename"` "[$temp1] -> [$i]"
 			continue
 		}
 	fi
-	echo "[OK]"
+	echo `gettext "[OK]"`
 	OKs=$((OKs+1))
 done
-echo "$OKs/$j rewrites succeeded"
+echo "$OKs/$j" `gettext "rewrites succeeded"`
 [ $OKs -ne $j ] && exit 1
 exit 0
diff --git a/src/utils/ecryptfs-setup-private b/src/utils/ecryptfs-setup-private
--- a/src/utils/ecryptfs-setup-private
+++ b/src/utils/ecryptfs-setup-private
@@ -10,7 +10,8 @@ PRIVATE_DIR="Private"
 WRAPPING_PASS="LOGIN"
 ECRYPTFS_DIR="/home/.ecryptfs"
 PW_ATTEMPTS=3
-MESSAGE="Enter your login passphrase"
+TEXTDOMAIN="ecryptfs-utils"
+MESSAGE=`gettext "Enter your login passphrase"`
 CIPHER="aes"
 KEYBYTES="16"
 FNEK=
@@ -19,42 +20,43 @@ FNEK=
 GREP_OPTIONS=
 
 usage() {
-	echo
-	echo "Usage:"
-	echo "  $0 [-f|--force] [-w|--wrapping] [--nopwcheck] [-n|--no-fnek]"
-	echo "  [-u|--username USER] [-l|--loginpass LOGINPASS]"
-	echo "  [-m|--mountpass MOUNTPASS]"
-	echo
-	echo " -f, --force      Force overwriting of an existing setup"
-	echo " -w, --wrapping   Use an independent wrapping passphrase,"
-	echo "                  different from the login passphrase"
-	echo " -n, --no-fnek    Do not encrypt filenames; If this flag is"
-	echo "                  omitted, and the kernel supports filename"
-	echo "                  encryption, then filenames will be encrypted"
-	echo " -u, --username   Username for encrypted private mountpoint,"
-	echo "                  defaults to yourself"
-	echo " -l, --loginpass  Login/Wrapping passphrase for USER,"
-	echo "                  used to wrap MOUNTPASS"
-	echo " --nopwcheck      Do not check the validity of the specified"
-	echo "                  login password (useful for LDAP user accounts)"
-	echo " --noautomount    Setup this user such that the encrypted private"
-	echo "                  directory is not automatically mounted on login"
-	echo " --noautoumount   Setup this user such that the encrypted private"
-	echo "                  directory is not automatically unmounted at"
-	echo "                  logout"
-	echo " -m, --mountpass  Passphrase for mounting the ecryptfs directory,"
-	echo "                  defaults to randomly generated $KEYBYTES bytes"
-	echo " -b, --bootstrap  Bootstrap a new user's entire home directory"
-	echo "                  Generates a random mount passphrase, which"
-	echo "			will be wrapped when the new login passphrase"
-	echo "			is set. SHOULD ONLY BE CALLED FROM 'adduser'."
-	echo " --undo           Provide instructions on how to undo an"
-	echo "                  encrypted private setup"
-	echo
-	echo "   Be sure to properly escape your parameters according to your"
-	echo "   shell's special character nuances, and also surround the"
-	echo "   parameters by double quotes, if necessary."
-	echo
+	echo "
+Usage:
+
+$0 [-f|--force] [-w|--wrapping] [--nopwcheck] [-n|--no-fnek]
+  [-u|--username USER] [-l|--loginpass LOGINPASS]
+  [-m|--mountpass MOUNTPASS]
+
+ -f, --force      Force overwriting of an existing setup
+ -w, --wrapping   Use an independent wrapping passphrase,
+                  different from the login passphrase
+ -n, --no-fnek    Do not encrypt filenames; If this flag is
+                  omitted, and the kernel supports filename
+                  encryption, then filenames will be encrypted
+ -u, --username   Username for encrypted private mountpoint,
+                  defaults to yourself
+ -l, --loginpass  Login/Wrapping passphrase for USER,
+                  used to wrap MOUNTPASS
+ --nopwcheck      Do not check the validity of the specified
+                  login password (useful for LDAP user accounts)
+ --noautomount    Setup this user such that the encrypted private
+                  directory is not automatically mounted on login
+ --noautoumount   Setup this user such that the encrypted private
+                  directory is not automatically unmounted at
+                  logout
+ -m, --mountpass  Passphrase for mounting the ecryptfs directory,
+                  defaults to randomly generated $KEYBYTES bytes
+ -b, --bootstrap  Bootstrap a new user's entire home directory
+                  Generates a random mount passphrase, which
+		  will be wrapped when the new login passphrase
+		  is set. SHOULD ONLY BE CALLED FROM 'adduser'.
+ --undo           Provide instructions on how to undo an
+                  encrypted private setup
+
+   Be sure to properly escape your parameters according to your
+   shell's special character nuances, and also surround the
+   parameters by double quotes, if necessary.
+"
 	exit 1
 }
 
@@ -79,7 +81,7 @@ you will need to very carefully perform the following actions manually:
 }
 
 error() {
-	echo "ERROR: $1" 1>&2
+	echo `gettext "ERROR:"` "$1" 1>&2
 	exit 1
 }
 
@@ -99,7 +101,7 @@ random_passphrase () {
 
 filename_encryption_available() {
 	version=$(cat /sys/fs/ecryptfs/version 2>/dev/null)
-	[ -z "$version" ] && error "Can't get ecryptfs version, ecryptfs kernel module not loaded?"
+	[ -z "$version" ] && error `gettext "Can't get ecryptfs version, ecryptfs kernel module not loaded?"`
 	[ $(($version & 0x100)) -eq 0 ] && return 1
 	return 0
 }
@@ -126,7 +128,7 @@ while [ ! -z "$1" ]; do
 		;;
 		-w|--wrapping)
 			WRAPPING_PASS="INDEPENDENT"
-			MESSAGE="Enter your wrapping passphrase"
+			MESSAGE=`gettext "Enter your wrapping passphrase"`
 			shift 1
 		;;
 		-f|--force)
@@ -150,7 +152,7 @@ while [ ! -z "$1" ]; do
 			exit 0
 		;;
 		-b|--bootstrap)
-			[ `whoami` = "root" ] || error "You must be root to bootstrap encrypt a home directory"
+			[ `whoami` = "root" ] || error `gettext "You must be root to bootstrap encrypt a home directory"`
 			BOOTSTRAP=1
 			MOUNTPASS=`random_passphrase $KEYBYTES`
 			RANDOM_MOUNTPASS=1
@@ -169,16 +171,16 @@ done
 # Prompt for the USER name, if not on the command line and not in the env
 if [ -z "$USER" ]; then
 	while [ true ]; do
-		echo -n "Enter the username: "
+		echo -n gettext `"Enter the username: "`
 		USER=`head -n1`
 		echo
 		if [ -z "$USER" ]; then
-			echo "ERROR: You must provide a username"
+			echo `gettext "ERROR: "` `gettext "You must provide a username"`
 			continue
 		else
 			# Verify that the user exists
 			if ! id "$USER" >/dev/null; then
-				echo "ERROR: User [$USER] does not exist"
+				echo `gettext "ERROR: "` `gettext "User does not exist"` " [$USER]"
 				continue
 			fi
 			break
@@ -186,20 +188,20 @@ if [ -z "$USER" ]; then
 	done
 else
 	# Verify that the user exists
-	id "$USER" >/dev/null || error "User [$USER] does not exist"
+	id "$USER" >/dev/null || error `gettext "User does not exist"` "[$USER]"
 fi
 
 # Check if the ecryptfs group exists, and user is member of ecryptfs group
 if grep -qs "^ecryptfs:" /etc/group; then
 	if ! id "$USER" | grep -qs "\(ecryptfs\)"; then
-	       error "User needs to be a member of ecryptfs group"
+	       error `gettext "User needs to be a member of ecryptfs group"`
 	fi
 fi
 
 # Obtain the user's home directory
 HOME=`getent passwd "$USER" | awk -F: '{print $6}'`
 if [ ! -d "$HOME" ]; then
-	error "User home directory [$HOME] does not exist"
+	error `gettext "User home directory does not exist"` "[$HOME]"
 fi
 
 if [ "$BOOTSTRAP" = "1" ]; then
@@ -218,26 +220,26 @@ fi
 
 # Check for previously setup private directory
 if [ -s "$HOME/.ecryptfs/wrapped-passphrase" -a "$FORCE" != "1" ]; then
-	error "wrapped-passphrase file already exists, use --force to overwrite."
+	error `gettext "wrapped-passphrase file already exists, use --force to overwrite."`
 fi
 if [ -s "$HOME/.ecryptfs/$PRIVATE_DIR.sig" -a "$FORCE" != "1" ]; then
-	error "$PRIVATE_DIR.sig file already exists, use --force to overwrite."
+	error "$PRIVATE_DIR.sig" `gettext "file already exists, use --force to overwrite."`
 fi
 
 # Check for active mounts
-grep -qs "$MOUNTPOINT " /proc/mounts && error "[$MOUNTPOINT] is already mounted"
-grep -qs "$CRYPTDIR " /proc/mounts && error "[$CRYPTDIR] is already mounted"
+grep -qs "$MOUNTPOINT " /proc/mounts && error "[$MOUNTPOINT]" `gettext "is already mounted"`
+grep -qs "$CRYPTDIR " /proc/mounts && error "[$CRYPTDIR]" `gettext "is already mounted"`
 
 # Check that the mount point and encrypted directory are empty (skip symlinks).
 # Perhaps one day we could provide a migration mode (using rsync or something),
 # but this would be VERY hard to do safely.
 count=`ls -Al "$MOUNTPOINT" 2>/dev/null | egrep -c "^[drwx-]{10}"`
 if [ "$count" != "0" ]; then
-	error "$MOUNTPOINT must be empty before proceeding"
+	error "$MOUNTPOINT" `gettext "must be empty before proceeding"`
 fi
 count=`ls -Al "$CRYPTDIR" 2>/dev/null | egrep -c "^[dlrwx-]{10}"`
 if [ "$count" != "0" ]; then
-	error "$CRYPTDIR must be empty before proceeding"
+	error "$CRYPTDIR" `gettext "must be empty before proceeding"`
 fi
 
 stty_orig=`stty -g`
@@ -259,7 +261,7 @@ if [ -z "$LOGINPASS" ] && [ "$BOOTSTRAP" != "1" ]; then
 			stty $stty_orig
 			echo
 			if [ "$LOGINPASS" != "$LOGINPASS2" ]; then
-				echo "ERROR: Wrapping passphrases must match"
+				echo `gettext "ERROR:"` `gettext "Wrapping passphrases must match"`
 			else
 				break
 			fi
@@ -267,25 +269,24 @@ if [ -z "$LOGINPASS" ] && [ "$BOOTSTRAP" != "1" ]; then
 			continue
 		fi
 		if [ -z "$LOGINPASS" ]; then
-			echo "ERROR: You must provide a login passphrase"
+			echo `gettext "ERROR:"` `gettext "You must provide a login passphrase"`
 			tries=$(($tries + 1))
 		else
 			if [ "$NOPWCHECK" = "1" ]; then
-				echo "INFO: Skipping password verification"
+				echo `gettext "INFO:"` `gettext "Skipping password verification"`
 				break
 			else
 				if printf "%s\0" "$LOGINPASS" | /sbin/unix_chkpwd "$USER" nullok; then
 					break
 				else
-					echo "ERROR: Your login passphrase is incorrect"
+					echo `gettext "ERROR:"` `getext "Your login passphrase is incorrect"`
 					tries=$(($tries + 1))
 				fi
 			fi
 		fi
 	done
 	if [ $tries -ge $PW_ATTEMPTS ]; then
-		echo "ERROR: Too many incorrect password attempts, exiting"
-		exit 1
+		error `gettext "Too many incorrect password attempts, exiting"`
 	fi
 fi
 
@@ -294,7 +295,7 @@ if [ -z "$MOUNTPASS" ]; then
 	tries=0
 	while [ $tries -lt $PW_ATTEMPTS ]; do
 		stty -echo
-		echo -n "Enter your mount passphrase [leave blank to generate one]: "
+		echo -n `gettext "Enter your mount passphrase [leave blank to generate one]: "`
 		MOUNTPASS=`head -n1`
 		stty $stty_orig
 		echo
@@ -304,12 +305,12 @@ if [ -z "$MOUNTPASS" ]; then
 			break
 		else
 			stty -echo
-			echo -n "Enter your mount passphrase (again): "
+			echo -n `gettext "Enter your mount passphrase (again): "`
 			MOUNTPASS2=`head -n1`
 			stty $stty_orig
 			echo
 			if [ "$MOUNTPASS" != "$MOUNTPASS2" ]; then
-				echo "ERROR: Mount passphrases do not match"
+				echo `gettext "ERROR:"` `gettext "Mount passphrases do not match"`
 				tries=$(($tries + 1))
 			else
 				break
@@ -317,48 +318,43 @@ if [ -z "$MOUNTPASS" ]; then
 		fi
 	done
 	if [ $tries -ge $PW_ATTEMPTS ]; then
-		echo "ERROR: Too many incorrect passphrase attempts, exiting"
-		exit 1
+		error `gettext "Too many incorrect passphrase attempts, exiting"`
 	fi
 fi
 
 echo
 echo "************************************************************************"
-if [ "$RANDOM_MOUNTPASS" = "1" ] && [ "$BOOTSTRAP" != "1" ]; then
-	echo "YOU SHOULD RECORD THIS MOUNT PASSPHRASE AND STORE IT IN A SAFE LOCATION:"
-	echo "$MOUNTPASS"
-else
-	echo "YOU SHOULD RECORD YOUR MOUNT PASSPHRASE AND STORE IT IN A SAFE LOCATION:"
-fi
-echo "THIS WILL BE REQUIRED IF YOU NEED TO RECOVER YOUR DATA AT A LATER TIME."
+echo `gettext "YOU SHOULD RECORD YOUR MOUNT PASSPHRASE AND STORE IT IN A SAFE LOCATION."`
+echo "  ecryptfs-unwrap-passphrase ~/.ecryptfs/wrapped-passphrase"
+echo `gettext "THIS WILL BE REQUIRED IF YOU NEED TO RECOVER YOUR DATA AT A LATER TIME."`
 echo "************************************************************************"
 echo
 
 ###############################################################################
 
 # Setup private directory in home
-mkdir -m 700 -p "$CRYPTDIR" || error "Could not create crypt directory [$CRYPTDIR]"
-mkdir -m 700 -p "$MOUNTPOINT" || error "Could not create mount directory [$MOUNTPOINT]"
+mkdir -m 700 -p "$CRYPTDIR" || error `gettext "Could not create crypt directory"` "[$CRYPTDIR]"
+mkdir -m 700 -p "$MOUNTPOINT" || error `gettext "Could not create mount directory"` "[$MOUNTPOINT]"
 ln -sf /usr/share/ecryptfs-utils/ecryptfs-mount-private.txt "$MOUNTPOINT"/README.txt
 ln -sf /usr/share/ecryptfs-utils/ecryptfs-mount-private.desktop "$MOUNTPOINT"/Access-Your-Private-Data.desktop
 chmod 500 "$MOUNTPOINT"
 
 # Setup ~/.ecryptfs directory
 if [ "$NOAUTOMOUNT" = "1" ]; then
-	echo "INFO: $HOME/$PRIVATE_DIR will not be mounted on login"
+	echo `gettext "INFO:"` "$HOME/$PRIVATE_DIR" `gettext "will not be mounted on login"`
 else
-	touch $HOME/.ecryptfs/auto-mount || error "Could not setup ecryptfs auto-mount"
+	touch $HOME/.ecryptfs/auto-mount || error `gettext "Could not setup ecryptfs auto-mount"`
 fi
 if [ "$NOAUTOUMOUNT" = "1" ]; then
-	echo "INFO: $HOME/$PRIVATE_DIR will not be unmounted on logout"
+	echo `gettext "INFO:"` "$HOME/$PRIVATE_DIR" `gettext "will not be unmounted on logout"`
 else
-	touch $HOME/.ecryptfs/auto-umount || error "Could not setup ecryptfs auto-umount"
+	touch $HOME/.ecryptfs/auto-umount || error `gettext "Could not setup ecryptfs auto-umount"`
 fi
 
 if [ "$WRAPPING_PASS" = "LOGIN" ]; then
-	rm -f $HOME/.ecryptfs/wrapping-independent || error "Could not remove ecryptfs wrapping-independent"
+	rm -f $HOME/.ecryptfs/wrapping-independent || error `gettext "Could not remove ecryptfs wrapping-independent"`
 else
-	touch $HOME/.ecryptfs/wrapping-independent || error "Could not setup ecryptfs wrapping-independent"
+	touch $HOME/.ecryptfs/wrapping-independent || error `gettext "Could not setup ecryptfs wrapping-independent"`
 fi
 
 
@@ -366,7 +362,7 @@ fi
 timestamp=`date +%Y%m%d%H%M%S`
 for i in "$HOME/.ecryptfs/wrapped-passphrase" "$HOME/.ecryptfs/$PRIVATE_DIR.sig"; do
 	if [ -s "$i" ]; then
-		mv -f "$i" "$i.$timestamp" || error "Could not backup existing data [$i]"
+		mv -f "$i" "$i.$timestamp" || error `gettext "Could not backup existing data"` "[$i]"
 	fi
 done
 
@@ -382,7 +378,7 @@ if [ "$BOOTSTRAP" = "1" ]; then
 	printf "%s" "$MOUNTPASS" > "$temp"
 	mv "$temp" "/dev/shm/.ecryptfs-$USER"
 else
-	printf "%s\n%s" "$MOUNTPASS" "$LOGINPASS" | ecryptfs-wrap-passphrase "$HOME/.ecryptfs/wrapped-passphrase" - || error "Could not wrap passphrase"
+	printf "%s\n%s" "$MOUNTPASS" "$LOGINPASS" | ecryptfs-wrap-passphrase "$HOME/.ecryptfs/wrapped-passphrase" - || error `gettext "Could not wrap passphrase"`
 fi
 umask $u
 
@@ -390,21 +386,21 @@ umask $u
 # On subsequent logins, this should be handled by "pam_ecryptfs.so unwrap"
 response=`printf "%s" "$MOUNTPASS" | ecryptfs-add-passphrase $FNEK -`
 if [ $? -ne 0 ]; then
-	error "Could not add passphrase to the current keyring"
+	error `gettext "Could not add passphrase to the current keyring"`
 fi
 sig=`echo "$response" | grep "Inserted auth tok" | sed "s/^.*\[//" | sed "s/\].*$//"`
 if ! echo "$sig" | egrep -qs "^[0-9a-fA-F]{$KEYBYTES,$KEYBYTES}$"; then
-	error "Could not obtain the key signature"
+	error `gettext "Could not obtain the key signature"`
 fi
 temp=`mktemp`
-echo "$sig" > "$temp" || error "Could not create signature file [$HOME/.ecryptfs/$PRIVATE_DIR.sig]"
+echo "$sig" > "$temp" || error `gettext "Could not create signature file"` "[$HOME/.ecryptfs/$PRIVATE_DIR.sig]"
 mv "$temp" "$HOME/.ecryptfs/$PRIVATE_DIR.sig"
 temp=`mktemp`
-echo "$MOUNTPOINT" > "$temp" || error "Could not create mountpoint file [$HOME/.ecryptfs/$PRIVATE_DIR.mnt]"
+echo "$MOUNTPOINT" > "$temp" || error `gettext "Could not create mountpoint file"` "[$HOME/.ecryptfs/$PRIVATE_DIR.mnt]"
 mv "$temp" "$HOME/.ecryptfs/$PRIVATE_DIR.mnt"
 
 echo
-echo "Done configuring."
+echo `gettext "Done configuring."`
 echo
 
 # Skip the tests if we're in bootstrap mode, but exit with the encrypted
@@ -434,26 +430,26 @@ if [ "$BOOTSTRAP" = "1" ]; then
 fi
 
 # Now let's perform some basic mount/write/umount/read sanity testing...
-echo "Testing mount/write/umount/read..."
-/sbin/mount.ecryptfs_private || error "Could not mount private ecryptfs directory"
-temp=`mktemp "$MOUNTPOINT/ecryptfs.test.XXXXXX"` || error_testing "$temp" "Could not create empty file"
-random_data=`head -c 16000 /dev/urandom | od -x` || error_testing "$temp" "Could not generate random data"
-echo "$random_data" > "$temp" || error_testing "$temp" "Could not write encrypted file"
-md5sum1=`md5sum "$temp"` || error_testing "$temp" "Could not read encrypted file"
-/sbin/umount.ecryptfs_private || error_testing "$temp" "Could not unmount private ecryptfs directory"
-/sbin/mount.ecryptfs_private || error_testing "$temp" "Could not mount private ecryptfs directory (2)"
-md5sum2=`md5sum "$temp"` || error_testing "$temp" "Could not read encrypted file (2)"
+echo `gettext "Testing mount/write/umount/read..."`
+/sbin/mount.ecryptfs_private || error `gettext "Could not mount private ecryptfs directory"`
+temp=`mktemp "$MOUNTPOINT/ecryptfs.test.XXXXXX"` || error_testing "$temp" `gettext "Could not create empty file"`
+random_data=`head -c 16000 /dev/urandom | od -x` || error_testing "$temp" `gettext "Could not generate random data"`
+echo "$random_data" > "$temp" || error_testing "$temp" `gettext "Could not write encrypted file"`
+md5sum1=`md5sum "$temp"` || error_testing "$temp" `gettext "Could not read encrypted file"`
+/sbin/umount.ecryptfs_private || error_testing "$temp" `gettext "Could not unmount private ecryptfs directory"`
+/sbin/mount.ecryptfs_private || error_testing "$temp" `gettext "Could not mount private ecryptfs directory (2)"`
+md5sum2=`md5sum "$temp"` || error_testing "$temp" `gettext "Could not read encrypted file (2)"`
 rm -f "$temp"
 # Use ecryptfs-umount-private on the final run, to clear the used keys
 # out of the keyring
-ecryptfs-umount-private || error_testing "$temp" "Could not unmount private ecryptfs directory (2)"
+ecryptfs-umount-private || error_testing "$temp" `gettext "Could not unmount private ecryptfs directory (2)"`
 if [ "$md5sum1" != "$md5sum2" ]; then
-	error "Testing failed."
+	error `gettext "Testing failed."`
 else
-	echo "Testing succeeded."
+	echo `gettext "Testing succeeded."`
 fi
 
 echo
-echo "Logout, and log back in to begin using your encrypted directory."
+echo `gettext "Logout, and log back in to begin using your encrypted directory."`
 echo
 exit 0
diff --git a/src/utils/ecryptfs-setup-swap b/src/utils/ecryptfs-setup-swap
--- a/src/utils/ecryptfs-setup-swap
+++ b/src/utils/ecryptfs-setup-swap
@@ -19,22 +19,24 @@
 # The cryptswap setup used here follows a guide published at:
 #  * http://ubuntumagnet.com/2007/11/creating-encrypted-swap-file-ubuntu-using-cryptsetup
 
+TEXTDOMAIN="ecryptfs-utils"
+
 error() {
-	echo "ERROR: $1" 1>&2
+	echo `gettext "ERROR:"` "$1" 1>&2
 	exit 1
 }
 
 info() {
-	echo "INFO: $1"
+	echo `gettext "INFO:"` "$1"
 }
 
 warning() {
-	echo "WARNING: "
+	echo `gettext "WARNING:"`
 }
 
 usage() {
 	echo
-	echo "Usage:"
+	echo `gettext "Usage:"`
 	echo "  $0 [-f|--force]"
 	echo
 	exit 1
@@ -55,41 +57,41 @@ while [ ! -z "$1" ]; do
 done
 
 # Ensure that cryptsetup is available
-[ -x /sbin/cryptsetup ] || error "Please install 'cryptsetup'"
+[ -x /sbin/cryptsetup ] || error `gettext "Please install"` "'cryptsetup'"
 
 # Ensure that we're running with root privileges
-[ -w /etc/passwd ] || error "This program must be run with 'sudo', or as root"
+[ -w /etc/passwd ] || error `gettext "This program must be run with 'sudo', or as root"`
 
 # Count swap spaces available
 # BUG: We only support setting up a single swap space at this time
 if [ $(grep -c "^/" /proc/swaps) -eq 0 ]; then
 	mem=$(grep "^MemTotal:" /proc/meminfo | awk '{print $2}')
 	swapsize=$((4*$mem))
-	info "You do not currently have any swap space defined."
+	info `gettext "You do not currently have any swap space defined."`
 	echo
-	echo "You can create a swap file by doing:"
+	echo `gettext "You can create a swap file by doing:"`
 	echo " $ sudo dd if=/dev/zero of=/swapfile count=$swapsize"
 	echo " $ sudo mkswap /swapfile"
 	echo " $ sudo swapon /swapfile"
 	echo
-	echo "And then re-run $0"
+	echo `gettext "And then re-run"` "$0"
 	echo
 	exit 0
 elif [ $(grep -c "^/" /proc/swaps) -gt 1 ]; then
-	info "You have more than one swap space defined."
-	error "$0 only supports setting up a single swap space"
+	info `gettext "You have more than one swap space defined."`
+	error "$0" `gettext "only supports setting up a single swap space"`
 else
 	swap=$(grep "^/" /proc/swaps | awk '{print $1}')
 fi
 
 # Make sure this is swap space
 if ! blkid "$swap" | grep -qs "TYPE=.*swap"; then
-	error "[$swap] does not appear to be swap space"
+	error "[$swap]" `gettext "does not appear to be swap space"`
 fi
 
 # Check if this this swap space is already setup for encryption
 if /sbin/dmsetup table "$swap" | grep -qs " crypt " 2>/dev/null; then
-	info "[$swap] already appears to be encrypted."
+	info "[$swap]" `gettext "already appears to be encrypted."`
 	exit 0
 else
 	# keep going
@@ -98,30 +100,30 @@ fi
 
 base=$(basename "$swap")
 if grep -qs "^$base.*swap.*cipher" /etc/crypttab 2>/dev/null; then
-	info "[$swap] already has an entry in /etc/crypttab."
+	info "[$swap]" `gettext "already has an entry in /etc/crypttab."`
 	exit 0
 fi
 if grep -qs "$swap" /etc/initramfs-tools/conf.d/cryptroot 2>/dev/null; then
-	info "[$swap] already has an entry in /etc/fstab."
+	info "[$swap]" `gettext "already has an entry in /etc/fstab."`
 	exit 0
 fi
 
 # Ensure available dev mapper name 'cryptswap'
 if grep -qs "^cryptswap" /etc/crypttab; then
-	error "There appears to be a cryptswap entry in /etc/cryptab; aborting."
+	error `gettext "There appears to be a cryptswap entry in /etc/cryptab; aborting."`
 fi
 
 # Ensure available fstab entry
 if grep -qs "^/dev/mapper/cryptswap" /etc/fstab; then
-	error "There appears to be a cryptswap entry in /etc/fstab; aborting."
+	error `gettext "There appears to be a cryptswap entry in /etc/fstab; aborting."`
 fi
 
 # Ensure that the existing swap space exists in fstab
 if grep -qs "^$swap" /etc/fstab; then
 	sed -i "s:^$swap:\#$swap:" /etc/fstab
-	info "Commented out your unencrypted swap from /etc/fstab"
+	info `gettext "Commented out your unencrypted swap from /etc/fstab"`
 else
-	info "Your swap space isn't currently listed in /etc/fstab"
+	info `gettext "Your swap space isn't currently listed in /etc/fstab"`
 fi
 
 ##########################################################################
@@ -129,20 +131,18 @@ fi
 if [ "$FORCE" != 1 ]; then
 	echo
 	warning
-	echo "    An encrypted swap is required to help ensure that encrypted files"
-	echo "    are not leaked to disk in an unencrypted format."
+	echo `gettext "An encrypted swap is required to help ensure that encrypted files are not leaked to disk in an unencrypted format."`
 	echo
-	echo "    HOWEVER, THE SWAP ENCRYPTION CONFIGURATION PRODUCED BY THIS PROGRAM"
-	echo "    WILL BREAK HIBERNATE/RESUME ON THIS SYSTEM!"
+	echo `gettext "HOWEVER, THE SWAP ENCRYPTION CONFIGURATION PRODUCED BY THIS PROGRAM WILL BREAK HIBERNATE/RESUME ON THIS SYSTEM!"`
 	echo
-	echo "    NOTE: Your suspend/resume capabilities will not be affected."
+	echo `gettext "NOTE: Your suspend/resume capabilities will not be affected."`
 	echo
-	echo -n "Do you want to proceed with encrypting your swap [y/N]: "
+	echo -n `gettext "Do you want to proceed with encrypting your swap?"` "[y/N]: "
 	CONFIRM=`head -n1`
 	echo
 	if [ "$CONFIRM" != "y" -a "$CONFIRM" != "Y" ]; then
 		echo
-		info "Aborting."
+		info `gettext "Aborting."`
 		echo
 		exit 0
 	fi
@@ -150,7 +150,7 @@ fi
 ##########################################################################
 
 
-info "Setting up swap: [$swap]"
+info `gettext "Setting up swap:"` "[$swap]"
 
 # Add crypttab entry
 echo "cryptswap $swap /dev/urandom swap,cipher=aes-cbc-essiv:sha256" >> /etc/crypttab
@@ -167,4 +167,4 @@ swapoff -a
 # Turn the swap on
 swapon -a
 
-info "Successfully setup encrypted swap!"
+info `gettext "Successfully setup encrypted swap!"`
