/sbin is not necessarily in the user's path

diff --git a/src/utils/ecryptfs-setup-private b/src/utils/ecryptfs-setup-private
--- a/src/utils/ecryptfs-setup-private
+++ b/src/utils/ecryptfs-setup-private
@@ -44,7 +44,7 @@ error() {
 
 error_testing() {
 	rm -f "$1" >/dev/null
-	umount.ecryptfs_private >/dev/null
+	/sbin/umount.ecryptfs_private >/dev/null
 	error "$2"
 	exit 1
 }
@@ -251,16 +251,16 @@ echo
 
 # Now let's perform some basic mount/write/umount/read sanity testing...
 echo "Testing mount/write/umount/read..."
-mount.ecryptfs_private || error "Could not mount private ecryptfs directory"
+/sbin/mount.ecryptfs_private || error "Could not mount private ecryptfs directory"
 temp=`mktemp "$HOME/$PRIVATE_DIR/ecryptfs.test.XXXXXX"` || error_testing "$temp" "Could not create empty file"
 random_data=`head -c 16000 /dev/urandom | od -x` || error_testing "$temp" "Could not generate random data"
 echo "$random_data" > "$temp" || error_testing "$temp" "Could not write encrypted file"
 md5sum1=`md5sum "$temp"` || error_testing "$temp" "Could not read encrypted file"
-umount.ecryptfs_private || error_testing "$temp" "Could not unmount private ecryptfs directory"
-mount.ecryptfs_private || error_testing "$temp" "Could not mount private ecryptfs directory (2)"
+/sbin/umount.ecryptfs_private || error_testing "$temp" "Could not unmount private ecryptfs directory"
+/sbin/mount.ecryptfs_private || error_testing "$temp" "Could not mount private ecryptfs directory (2)"
 md5sum2=`md5sum "$temp"` || error_testing "$temp" "Could not read encrypted file (2)"
 rm -f "$temp"
-umount.ecryptfs_private || error_testing "$temp" "Could not unmount private ecryptfs directory (2)"
+/sbin/umount.ecryptfs_private || error_testing "$temp" "Could not unmount private ecryptfs directory (2)"
 if [ "$md5sum1" != "$md5sum2" ]; then
 	error "Testing failed."
 else
