* SECURITY UPDATE: privilege escalation via mountpoint race conditions   (LP: #732628)   - debian/patches/CVE-2011-1831,1832,1834.patch: chdir into mountpoint     before checking permissions in src/utils/mount.ecryptfs_private.c.   - CVE-2011-1831   - CVE-2011-1832 * SECURITY UPDATE: race condition when checking source during mount   (LP: #732628)   - debian/patches/CVE-2011-1833.patch: use new ecryptfs_check_dev_ruid     kernel option when mounting directory in     src/utils/mount.ecryptfs_private.c.   - CVE-2011-1833 * SECURITY UPDATE: mtab corruption via improper handling (LP: #732628)   - debian/patches/CVE-2011-1831,1832,1834.patch: modify mtab via a temp     file first and make sure it succeeds before replacing the real mtab     in src/utils/mount.ecryptfs_private.c.   - CVE-2011-1834 * SECURITY UPDATE: key poisoning via insecure temp directory handling   (LP: #732628)   - debian/patches/CVE-2011-1835.patch: make sure we don't copy into a     user controlled directory in src/utils/ecryptfs-setup-private.   - CVE-2011-1835 * SECURITY UPDATE: information disclosure via recovery mount in /tmp   (LP: #732628)   - debian/patches/CVE-2011-1836.patch: mount inside protected     subdirectory in src/utils/ecryptfs-recover-private.   - CVE-2011-1836 * SECURITY UPDATE: arbitrary file overwrite via lock counter race   condition (LP: #732628)   - debian/patches/CVE-2011-1837.patch: verify permissions with a file     descriptor, and don't follow symlinks in     src/utils/mount.ecryptfs_private.c.   - CVE-2011-1837

diff --git a/src/utils/ecryptfs-setup-private b/src/utils/ecryptfs-setup-private
--- a/src/utils/ecryptfs-setup-private
+++ b/src/utils/ecryptfs-setup-private
@@ -380,7 +380,7 @@ if [ "$BOOTSTRAP" = "1" ]; then
 	# ramdisk, to keep it from leaking to the hard-drive.
 	temp=`mktemp /dev/shm/.ecryptfs-XXXXXX`
 	printf "%s" "$MOUNTPASS" > "$temp"
-	mv "$temp" "/dev/shm/.ecryptfs-$USER"
+	mv -f -T "$temp" "/dev/shm/.ecryptfs-$USER" || error "Could not create passphrase file"
 else
 	printf "%s\n%s" "$MOUNTPASS" "$LOGINPASS" | ecryptfs-wrap-passphrase "$HOME/.ecryptfs/wrapped-passphrase" - || error "$(gettext 'Could not wrap passphrase')"
 fi
