src/utils/ecryptfs-setup-private: fix printing of error strings, which was broken by the gettext integration, LP: #471725

diff --git a/src/utils/ecryptfs-setup-private b/src/utils/ecryptfs-setup-private
--- a/src/utils/ecryptfs-setup-private
+++ b/src/utils/ecryptfs-setup-private
@@ -81,14 +81,15 @@ you will need to very carefully perform the following actions manually:
 }
 
 error() {
-	echo `gettext "ERROR:"` "$1" 1>&2
+	echo `gettext "ERROR:"` "$@" 1>&2
 	exit 1
 }
 
 error_testing() {
 	rm -f "$1" >/dev/null
+	shift
 	/sbin/umount.ecryptfs_private >/dev/null
-	error "$2"
+	error "$@"
 	exit 1
 }
 
